server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "${ALLOWED_ORIGINS:http://localhost:5173}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true

      # ROUTES
      routes:
        - id: parties-service
          uri: ${PARTIES_SERVICE_URL:http://localhost:5000}
          predicates:
            - Path=/api/parties/**

        # Route for Java Trading Service
        - id: trading-service
          uri: ${TRADING_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/trading/**

        # Route for Java Auth Service
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/auth/**

        # Route for Node.js Smart Ops
        - id: smart-ops-service
          uri: ${SMARTOPS_SERVICE_URL:http://localhost:5002}
          predicates:
            - Path=/api/smart-ops/**